pub fn get_language_code(lang: &str) -> &'static str {
    match lang {
        "English" => "en",
        "Spanish" => "es",
        "French" => "fr",
        "German" => "de",
        "Italian" => "it",
        "Dutch" => "nl",
        "Portuguese" => "pt",
        "Russian" => "ru",
        "Japanese" => "ja",
        "Chinese" => "zh",
        "Korean" => "ko",
        "Arabic" => "ar",
        "Turkish" => "tr",
        "Polish" => "pl",
        "Swedish" => "sv",
        "Danish" => "da",
        "Finnish" => "fi",
        "Norwegian" => "no",
        "Greek" => "el",
        "Hebrew" => "he",
        "Indonesian" => "id",
        "Ukrainian" => "uk",
        "Thai" => "th",
        "Czech" => "cs",
        "Hindi" => "hi",
        "Bengali" => "bn",
        "Croatian" => "hr",
        "Hungarian" => "hu",
        "Malay" => "ms",
        "Romanian" => "ro",
        "Slovak" => "sk",
        "Vietnamese" => "vi",
        "Catalan" => "ca",
        "Filipino" => "fil",
        "Serbian" => "sr",
        "Lithuanian" => "lt",
        "Slovenian" => "sl",
        "Latvian" => "lv",
        "Estonian" => "et",
        "Maltese" => "mt",
        "Icelandic" => "is",
        "Albanian" => "sq",
        "Macedonian" => "mk",
        "Swahili" => "sw",
        "Welsh" => "cy",
        "Basque" => "eu",
        "Galician" => "gl",
        "Scots Gaelic" => "gd",
        "Breton" => "br",
        "Corsican" => "co",
        "Azerbaijani" => "az",
        "Armenian" => "hy",
        "Georgian" => "ka",
        "Kazakh" => "kk",
        _ => "en"
    }
}

pub fn get_platform_cropping(platform: &str) -> (f64, f64, f64, f64) {
    match platform {
        "Netflix" => (0.0, 0.6, 1.0, 0.28),
        "Hulu" => (0.29, 0.6, 0.42, 0.37),
        "Amazon Prime Video" => (0.25, 0.04, 0.50, 0.92),
        "Disney+" => (0.15, 0.03, 0.7, 0.94),
        "Max" => (0.15, 0.03, 0.7, 0.91),
        "YouTube" => (0.18, 0.7, 0.64, 0.3),
        "AppleTV" => (0.23, 0.03, 0.54, 0.90),
        _ => (0.15, 0.03, 0.7, 0.94)
    }
}